---
--- Generated by Luanalysis
--- Created by ben.
--- DateTime: 2021/9/27 9:01 下午
---
-- Auto translate issue to English
--[[
on('IssueEvent', function (e)
    if (e.action == 'opened') then
        print("test---------------------------------------------")
        translate(e.title, 'en', function(translatedTitle)
            local commentHeader = ''
            local commentTitle = ''
            local commentHeader = renderString(config['issue-english-translator'].header, {author=e.author})
            local commentTitle = renderString(config['issue-english-translator'].title, {title=translatedTitle})

            translate(e.body, 'en', function(translatedBody)
                if ( translatedTitle ~= e.title or translatedBody ~= e.body)
                then
                    local commentBody = ''
                    local commentBody = renderString(config['issue-english-translator'].body, {body=translatedBody})
                    local comment = commentHeader .. commentTitle .. commentBody
                    addIssueComment(e.number, comment)
                    print('Issue #' .. e.number .. 'translate done ')
                else
                    print('No translate need for issue #' .. e.number)
                end
                if ( translatedTitle ~= e.title ) then
                    updateIssue(e.number, {title=translatedTitle})
]]
--[[translatedTitle就是翻译后的内容                    ]]--[[

                    print('translatedTitle'..translatedTitle)
                    print('Issue #' .. e.number .. ' title moidfy done ')
                end
            end)
        end)
    end
end)
]]
